using FluentAssertions;
using LangTeach.Api.AI;
using LangTeach.Api.Services;
using Microsoft.Extensions.Logging.Abstractions;

namespace LangTeach.Api.Tests.AI;

public class RedaccionCorrectionPromptBuilderTests
{
    private readonly RedaccionCorrectionPromptBuilder _builder;

    public RedaccionCorrectionPromptBuilderTests()
    {
        var sps = new SectionProfileService(NullLogger<SectionProfileService>.Instance);
        var pedagogy = new PedagogyConfigService(NullLogger<PedagogyConfigService>.Instance, sps);
        _builder = new RedaccionCorrectionPromptBuilder(pedagogy, NullLogger<RedaccionCorrectionPromptBuilder>.Instance);
    }

    [Fact]
    public void Build_WithFrenchAndDifficulties_IncludesAllPersonalizationBlocks()
    {
        var ctx = new RedaccionCorrectionPromptContext(
            StudentText: "Yo soy ir al cine.",
            StudentL1: "French",
            StudentDifficulties: new[] { "ser vs estar", "preposiciones a/en" },
            AssignmentPrompt: "Describe tu fin de semana.");

        var req = _builder.BuildWithTool(ctx).Request;

        req.Model.Should().Be(ClaudeModel.Sonnet);
        req.SystemPrompt.Should().Contain("Cohesión");
        req.SystemPrompt.Should().Contain("Ortografía");
        req.UserPrompt.Should().Contain("L1 INTERFERENCE: the student's native language is French");
        req.UserPrompt.Should().Contain("WEAK POINTS TO WATCH");
        req.UserPrompt.Should().Contain("ser vs estar");
        req.UserPrompt.Should().Contain("ASSIGNMENT CONTEXT: Describe tu fin de semana.");
        req.UserPrompt.Should().Contain("STUDENT TEXT");
        req.UserPrompt.Should().Contain("Yo soy ir al cine.");
    }

    [Fact]
    public void Build_NoL1NoDifficultiesNoPrompt_OmitsOptionalBlocks()
    {
        var ctx = new RedaccionCorrectionPromptContext(
            StudentText: "Texto del estudiante.",
            StudentL1: null,
            StudentDifficulties: Array.Empty<string>(),
            AssignmentPrompt: null);

        var req = _builder.BuildWithTool(ctx).Request;

        req.UserPrompt.Should().NotContain("L1 INTERFERENCE");
        req.UserPrompt.Should().NotContain("WEAK POINTS TO WATCH");
        req.UserPrompt.Should().NotContain("ASSIGNMENT CONTEXT");
    }

    [Fact]
    public void Build_NoStudentLevelOrCalibrationInUserPrompt()
    {
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.UserPrompt.Should().NotContain("STUDENT LEVEL:", "Pass 1 is level-agnostic");
        req.UserPrompt.Should().NotContain("Calibration:", "Pass 1 is level-agnostic");
    }

    [Fact]
    public void Build_NoMuyBienInSystemPrompt()
    {
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().NotContain("MuyBien", "Pass 1 emits C/G/L/O only; MuyBien is generated by Pass 2");
    }

    [Fact]
    public void Build_SystemPromptContainsSerEstarCriticalRule()
    {
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().Contain("ser/estar", "ser/estar must be in CRITICAL RULES at every level");
        req.SystemPrompt.Should().Contain("every level", "the rule applies regardless of CEFR");
    }

    [Fact]
    public void Build_OExampleUsesMusica_NotEsta()
    {
        // Issue #1210: the old O example used "esta"/"está" which directly conflicts with the
        // ser/estar G rule. The model pattern-matched the example and misclassified the error.
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().Contain("musica", "O example must use musica/música so it cannot be confused with a ser/estar grammar error");
        req.SystemPrompt.Should().NotContain("\"*esta*\" instead of \"está\" → O", "the ambiguous esta/está O example must be removed");
    }

    [Fact]
    public void Build_SystemPromptContainsSerEstarDecisionTree()
    {
        // Issue #1215: the three accumulated ser/estar rules are replaced with one decision tree.
        // The decision tree has an explicit G path ("esta" → "es") and O path (accent-only).
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().Contain("never omit", "ser/estar rule must mandate tagging every occurrence");
        req.SystemPrompt.Should().Contain("es común", "ser/estar rule must reference ser for cultural norms");
        req.SystemPrompt.Should().Contain("\"esta\" corrected to \"es\"", "G path must show esta→es as the example");
    }

    [Fact]
    public void Build_SerEstarRuleReferencesGeneralCharacteristics()
    {
        // Issue #1210: "permanent/transient" framing is imprecise and leads to wrong
        // classifications. The strengthened rule anchors on general characteristics/norms.
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().Contain("general characteristics", "ser/estar rule must use general-characteristics framing");
        req.SystemPrompt.Should().Contain("cultural norms", "ser/estar rule must reference cultural norms as a ser anchor");
    }

    [Fact]
    public void Build_SystemPromptContainsRegisterMismatchInL()
    {
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().Contain("register mismatch", "[L] must cover register mismatch as well as calques");
    }

    [Fact]
    public void Build_DifficultiesCappedAtThree()
    {
        var ctx = MakeCtx() with
        {
            StudentDifficulties = new[] { "one", "two", "three", "four", "five" },
        };

        var prompt = _builder.BuildWithTool(ctx).Request.UserPrompt;
        prompt.Should().Contain("- one");
        prompt.Should().Contain("- two");
        prompt.Should().Contain("- three");
        prompt.Should().NotContain("- four");
        prompt.Should().NotContain("- five");
    }

    [Fact]
    public void Build_SetsTemperatureToZero_ForVerbatimFidelity()
    {
        // Issue #1166: temperature=0 is the primary fix for the "model paraphrases
        // originalText on long inputs" failure mode. Removing this would re-open the bug.
        var req = _builder.BuildWithTool(MakeCtx()).Request;
        req.Temperature.Should().Be(0);
    }

    [Fact]
    public void Build_SetsMaxTokensTo32768_ToPreventTruncationOnA1Content()
    {
        // Issue #1217: raised to 8192; #1219: raised to 16384; #1293: raised to 32768 because
        // A1 students with 30+ errors in 150 words can exceed 16384 output tokens once
        // Hardening II prompt additions (#1222/#1226/#1227) increased per-tag verbosity.
        var req = _builder.BuildWithTool(MakeCtx()).Request;
        req.MaxTokens.Should().Be(32768);
    }

    [Fact]
    public void Build_WrapsStudentTextInVerbatimMarkers()
    {
        // Markers use a per-request nonce ("STUDENT_TEXT_VERBATIM_<guid>") so they cannot
        // collide with user-controlled student text. The label tells the model that tag
        // offsets must reference this text exactly.
        var ctx = MakeCtx() with { StudentText = "Hoy ablar con mi amigo." };
        var prompt = _builder.BuildWithTool(ctx).Request.UserPrompt;

        prompt.Should().MatchRegex("<<<STUDENT_TEXT_VERBATIM_[0-9a-f]{32}>>>");
        prompt.Should().MatchRegex("<<</STUDENT_TEXT_VERBATIM_[0-9a-f]{32}>>>");
        prompt.Should().Contain("Hoy ablar con mi amigo.");
        prompt.Should().Contain("offsets must reference this text exactly");
    }

    [Fact]
    public void Build_RegeneratesMarker_WhenStudentTextContainsCollidingMarker()
    {
        // Sanity check: even if the student happened to write a string matching the marker
        // pattern, the builder must regenerate. We can't easily force a collision without
        // mocking Guid.NewGuid; instead verify two builds produce DIFFERENT marker nonces
        // (proves the marker isn't a global constant) and that marker-suffix bytes from one
        // run don't appear in another build's output.
        var prompt1 = _builder.BuildWithTool(MakeCtx() with { StudentText = "First text." }).Request.UserPrompt;
        var prompt2 = _builder.BuildWithTool(MakeCtx() with { StudentText = "Second text." }).Request.UserPrompt;

        var marker1 = System.Text.RegularExpressions.Regex.Match(prompt1, "STUDENT_TEXT_VERBATIM_[0-9a-f]{32}").Value;
        var marker2 = System.Text.RegularExpressions.Regex.Match(prompt2, "STUDENT_TEXT_VERBATIM_[0-9a-f]{32}").Value;
        marker1.Should().NotBe(marker2);
    }

    [Fact]
    public void Build_SystemPromptInstructsIndexOfOffsetDerivation()
    {
        // Issue #1175: the OFFSETS section must instruct the model to use string search
        // (indexOf) to derive startIndex, NOT counting forward from position 0. Counting
        // is unreliable near accented chars (é, ó, á, ñ). Removing this instruction
        // re-opens the silent tag-drop bug.
        var req = _builder.BuildWithTool(MakeCtx()).Request;
        req.SystemPrompt.Should().Contain("indexOf", "OFFSETS must reference indexOf/string-search derivation");
        req.SystemPrompt.Should().Contain("accented", "OFFSETS must warn about accented characters");
    }

    [Fact]
    public void Build_SystemPromptContainsMinimumSpanRule()
    {
        // Issue #1215: the OFFSETS block must contain a general minimum-span rule so the model
        // spans only the erroneous morpheme, not surrounding context.
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().Contain("minimum substring", "OFFSETS must mandate minimum-span tagging");
        req.SystemPrompt.Should().Contain("interesante", "minimum-span rule must include the gender-agreement example");
        req.SystemPrompt.Should().Contain("interesantes", "minimum-span example must show the corrected plural form");
    }

    [Fact]
    public void Build_SystemPromptContainsDiscourseOrganizationInCCategory()
    {
        // Issue #1226: C must cover discourse-level errors (paragraph structure, topic
        // sentences, logical ordering) not just connectors, per EOI Coherencia y Cohesión rubric.
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().Contain("Cohesión y Coherencia", "C must be labelled as CCoh, covering both connector and discourse errors");
        req.SystemPrompt.Should().Contain("topic sentence", "C must include topic-sentence absence as a discourse-level example");
        req.SystemPrompt.Should().Contain("logically ordered", "C must include logical ordering as a discourse-level error");
    }

    [Fact]
    public void Build_SystemPromptContainsParagraphBreakSubtype()
    {
        // Issue #1350: C must cover paragraph-break errors (B1+) so the model can flag
        // a wall of text that should be split into paragraphs per the EOI rubric.
        var req = _builder.BuildWithTool(MakeCtx()).Request;

        req.SystemPrompt.Should().Contain("Paragraph-break", "C must include paragraph-break as a B1+ subtype");
        req.SystemPrompt.Should().Contain("B1 and above", "paragraph-break gating must be explicit in the subtype");
        req.SystemPrompt.Should().Contain("¶", "correctedForm for paragraph-break must be the pilcrow symbol");
    }

    private static RedaccionCorrectionPromptContext MakeCtx() =>
        new("Texto.", null, Array.Empty<string>(), null);
}
